/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Controlador.VisitaTableModelResultSet;
import clasesdata.Conexion;
import clasesprincipales.VisitaDeAtencion;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author MrLyoto
 */
public class VistaVisitaMain extends javax.swing.JPanel {

    /**
     * Creates new form VistaVisitaMain
     */
    public VistaVisitaMain() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonMostrarTodo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxBuscar = new javax.swing.JComboBox<>();
        jTextFieldBuscar = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVisitas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonBorrar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(500, 500));
        setLayout(new java.awt.BorderLayout());

        jButtonMostrarTodo.setText("Mostrar Todas las visitas");
        jButtonMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarTodoActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar por: ");

        jComboBoxBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre de mascota", "DNI del dueño" }));

        jTextFieldBuscar.setColumns(15);

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, Short.MAX_VALUE)
                .addComponent(jButtonMostrarTodo)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jButtonBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jComboBoxBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonMostrarTodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBorder(null);

        jTableVisitas.setAutoCreateRowSorter(true);
        jTableVisitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableVisitas);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButtonBorrar.setText("Borrar");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEditar)
                .addGap(18, 18, 18)
                .addComponent(jButtonBorrar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBorrar)
                    .addComponent(jButtonEditar))
                .addGap(5, 5, 5))
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarTodoActionPerformed
        String buscar = "1";
        VisitaTableModelResultSet tableModel = new VisitaTableModelResultSet(buscar);

        getjTable1().setModel(tableModel);
        getjTable1().repaint();

    }//GEN-LAST:event_jButtonMostrarTodoActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        String buscar, tipo, valor;
        if (jComboBoxBuscar.getSelectedItem() == "Nombre de mascota") {
            tipo = "m.alias";
        } else {
            tipo = "";
        }
        if (jComboBoxBuscar.getSelectedItem() == "DNI del dueño") {
            tipo = "c.dni_cliente";
        }

        buscar = tipo + " like " + "'" + jTextFieldBuscar.getText() + "'";

        VisitaTableModelResultSet tableModel = new VisitaTableModelResultSet(buscar);

        getjTable1().setModel(tableModel);
        getjTable1().repaint();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        try {
            int selectedRow = jTableVisitas.getSelectedRow();
            if (selectedRow > 0) {
                int idVisita = (int) jTableVisitas.getModel().getValueAt(selectedRow, 0);
                String sql = "delete from visita where id_visita = ?;";
                PreparedStatement ps = Conexion.getConexion().prepareStatement(sql);
                ps.setInt(1, idVisita);
                if (ps.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "Visita borrada");
                }
                jButtonMostrarTodoActionPerformed(evt);
            } else {
                JOptionPane.showMessageDialog(null, "Por favor seleccione una visita para borrarla.");
            }

        } catch (Exception ex) {
            int stackNumber = 0;
            for (int i = 0; i < ex.getStackTrace().length; i++) {
                if ("<init>".equals(ex.getStackTrace()[i].getMethodName())) {
                    stackNumber = i - 1;
                }
            }
            System.out.println("*******************************************************");
            System.out.println("Error al borrar visita");
            System.out.println(ex);
            System.out.println("Error en: " + ex.getStackTrace()[stackNumber].getClassName() + " ---> " + ex.getStackTrace()[stackNumber].getMethodName() + " || Line: " + ex.getStackTrace()[stackNumber].getLineNumber());
            System.out.println("*******************************************************");
        }

    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        VisitaDeAtencion visita = new VisitaDeAtencion();
        int selectedRow = jTableVisitas.getSelectedRow();
        if (selectedRow >= 0) {
            int idVisita = (int) jTableVisitas.getModel().getValueAt(selectedRow, 0);
            String sql = "select * from visita where id_Visita = ?;";
            try (PreparedStatement ps = Conexion.getConexion().prepareStatement(sql)) {
                ps.setInt(1, idVisita);
                ResultSet rs = ps.executeQuery();
                rs.next();
                visita.setIdVisita(rs.getInt("id_visita"));
                visita.setIdTratamiento(rs.getInt("id_tratamiento1"));
                visita.setIdMascota(rs.getInt("id_masc1"));
                visita.setFecha(rs.getDate("fecha"));
                visita.setPrecio(rs.getDouble("precio"));
                
                VistaVisitaEditar vistaEditar = new VistaVisitaEditar(visita);
                vistaEditar.setVisible(true);
            } catch (Exception ex) {
                int stackNumber = 0;
                for (int i = 0; i < ex.getStackTrace().length; i++) {
                    if ("<init>".equals(ex.getStackTrace()[i].getMethodName())) {
                        stackNumber = i - 1;
                    }
                }
                System.out.println("*******************************************************");
                System.out.println("");
                System.out.println(ex);
                System.out.println("Error en: " + ex.getStackTrace()[stackNumber].getClassName() + " ---> " + ex.getStackTrace()[stackNumber].getMethodName() + " || Line: " + ex.getStackTrace()[stackNumber].getLineNumber());
                System.out.println("*******************************************************");

            }

        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonMostrarTodo;
    private javax.swing.JComboBox<String> jComboBoxBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVisitas;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables

    public JButton getjButton1() {
        return jButtonMostrarTodo;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JTable getjTable1() {
        return jTableVisitas;
    }

}
